version: "3.8"
services:
  firstservice:
    image: kade:1.0
    ports:
      - 3000:3000
    deploy:
      replicas: 3
  secondservice:
    image: kade:1.0
    ports:
      - 3001:3000
    deploy:
      replicas: 2